// <auto-generated />
namespace ASP_NET_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class coursetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coursetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261303272_coursetable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
