// <auto-generated />
namespace ASP_NET_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SummaryAddToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SummaryAddToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261429445_SummaryAddToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
